name: Merge Python Requirements Upgrade PRs for EDX org

on:
  schedule:
    # will run the job at 10 AM every day (UTC),
    # https://crontab.guru/#0_10_*_*_*
    - cron: "0 10 * * *"
  workflow_dispatch:


jobs:
  call-automerge-prs-workflow:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Script
        run: |
          mkdir -p scripts
          cd scripts
          wget https://raw.githubusercontent.com/zubairshakoorarbisoft/.github/master/scripts/get_ready_to_merge_prs.py

      - name: Merge Requirements Upgrade PRs
        uses: zubairshakoorarbisoft/.github/.github/workflows/merge-python-requirements-upgrade-prs.yml@master
        with:
          ORG_NAME: "edx"
